### ISSUE TITLE
example for docker events

### ISSUE THREAD

**Issue by shomodj** [AgustinCB/docker-api#10]
Hey,

is it possible to create an example/docs on how to watch for all docker events?

Thanks

**Comment by AgustinCB** [comment]
Yes, it's. Will add it.

**Comment by shomodj** [comment]
Thanks, I tried, but could not get any events :(

**Comment by AgustinCB** [comment]
I see there's no test for that also. It may easily be a bug. Will research a little bit later and try to fix it. Good catch, thank you.

**Comment by AgustinCB** [comment]
Let me know if that's enough :). You will have to update the version.

**Comment by shomodj** [comment]
Yep, this works, thanks.
