### ISSUE TITLE
id undefined

### ISSUE THREAD

**Issue by dcharbonnier** [AgustinCB/docker-api#11]
what is this "id" ? its undefined on https://github.com/AgustinCB/docker-api/blob/master/src/plugin.js#L53

**Comment by AgustinCB** [comment]
This is actually a valid error, will reopen and fix. Thank you for reporting!

**Comment by AgustinCB** [comment]
`id` should be the name of the plugin to upgrade. Usage:

`docker.plugin.upgrade({}, 'plugin')`
