### ISSUE TITLE
[proposal] remove the confusion between the class and instance access

### ISSUE THREAD

**Issue by dcharbonnier** [AgustinCB/docker-api#14]
Example of implementation for the Exec class
https://github.com/dcharbonnier/docker-api/commit/78b2f22cb46b2e4f919c43f2e79d124e451181bd
The file may be easier to read [container.ts](https://github.com/dcharbonnier/docker-api/blob/78b2f22cb46b2e4f919c43f2e79d124e451181bd/src/container.ts)

Example of use :
```typescript
const container = new Container(new Modem({}), "e90e34656806");

const exec = container.exec.get(SAVER_EXEC_ID);
await exec.resize({h: 10, w : 5});
let status = await exec.status();
console.log(`This exec is ${status.Running ? "" : "not "} running`);

const execLs = await container.exec.create({ Cmd: "ls /", AttachStdout: true});
const stream = await execLs.start();
stream.on("data", (data: Buffer) => console.log(data.toString()));
stream.on("end", () => console.log("ls done"));
```

**Comment by AgustinCB** [comment]
Sorry, I'm not sure I'm following you. Can you put an example of after and before so I can get a better idea?

**Comment by dcharbonnier** [comment]
When we call for example a create with an id, we are using a kind of 'side'
effect of the instance,the instance is just used because we need the
container and the modem. Its 'convenient'  but not really what we expect.
Same thing when we create the new Exec with no id, the instance has never
intented to 'really' be an instance of exec. Using static methods is not
convenient because it would force to pass too many arguments all the times.
The pattern of having a private constructor and a manager created
statically address this question of 'consistency', meaning that the class
is doing what we could expect and also make the arguments more 'clear'
because you always have an effect on the instance and you never call a
method on a 'fake' instance.

Not sure to be clear, trying on a different way, the container.exec is not
a real exec on the contaimer but its an Exec object the return of the
exec.create return an Exec which is a real exec on the container so a kind
of constructor. Is exec a recursive structure? No, it make no sense.

**Comment by AgustinCB** [comment]
Uhm, I think I follow you.

So you're suggesting to break the Exec object into two different objects. One, called for example ExecManager, that handles actions that aren't performed on instances of Exec and another one that it's a representation of the Exec concept.

I see where you're coming from. It's a valid point. Some comments:

1. When I thought of that, I designed the Exec object to be a representation of exec API and not a representation of an Exec. It was meant to be a simple helper. If that helper was created with an id, then you don't have to pass a lot of parameters.

2. I'm not sure there's really side effects: Every action returns newly created object, so the previous should still behave as it was intended (I was very careful about that).

3. I'd prefer to maintain abstraction over the idea of IDs. It really doesn't make sense to have the ID of exec laying around, as they are supposed to be one use concepts. It makes more sense:

```javascript
const exec = await container.exec.create({})
exec.start()
```

Than:

```javascript
const exec = container.exec.get('some id')
```

And while it's true that in other Docker API it does make sense to give the user control over ids, I still prefer the design in which that's abstracted. 

I don't mind change my mind around the point 1. It isn't settled in stone and adding some abstraction makes some sense.

I do mind change the point 2.

So my conclusion is: As long as it doesn't change the interface (i.e. as long as the tests and examples still work as they are written now), I don't mind this change. And it even makes some sense, now that we have a proper type inference system.

I'll take of this task though, would like to give it a little more thoughts. 

Thank you for the feedback.

**Comment by dcharbonnier** [comment]
> When I thought of that, I designed the Exec object to be a representation of exec API and not a representation of an Exec. It was meant to be a simple helper. If that helper was created with an id, then you don't have to pass a lot of parameters.

Storing the id, doing an Object.assign, ... break that

> I'm not sure there's really side effects: Every action returns newly created object, so the previous should still behave as it was intended (I was very careful about that).

I don't get this point, on the Exec the only thing that return an Exec is the create, the contructor return an Exec but it's a fake one that has no id and it you call start() on it you will get an unexpected behavior because this object it not able to "start", the one returned by create is... confusing...

> I'd prefer to maintain abstraction over the idea of IDs. It really doesn't make sense to have the ID of exec laying around, as they are supposed to be one use concepts. It makes more sense:

Me too, and the proposal make way more sense, because you can't pass ID on the methods like on the current implementation, the goal is not to make .get all the time, most of the time you do create or you already have the object coming from a list but if you store this ID on a database for example or send it on a rest api you need a way to make this object.

About the tests and not having any changes I don't think it's so important at this stage of development but the test still pass with my changes and it's scary ;-)
Anyway let's see what you do
