### ISSUE TITLE
service.update, remove and status is undefined

### ISSUE THREAD

**Issue by kanedauy** [AgustinCB/docker-api#18]
Using version 1.1.8

[service.md](https://github.com/AgustinCB/docker-api/blob/master/docs/service.md)

```javascript
const Docker = require('node-docker-api').Docker
const docker = new Docker({
  socketPath: '/var/run/docker.sock'
})

typeof docker.service.update === 'undefined'
typeof docker.service.remove === 'undefined'
typeof docker.service.status === 'undefined'
```

**Comment by AgustinCB** [comment]
Yeah, it's expected. Usage:

```javascript
const Docker = require('node-docker-api').Docker
const docker = new Docker({
  socketPath: '/var/run/docker.sock'
})

typeof docker.service.get(SERVICE_ID) !== 'undefined'
```

See also: https://github.com/AgustinCB/docker-api/blob/master/test/swarm.js#L94

**Comment by kanedauy** [comment]
Then service.md is not right?
Do I do something like this?
```javascript
const Docker = require('node-docker-api').Docker
const docker = new Docker({
  socketPath: '/var/run/docker.sock'
})

docker.service.get(SERVICE_ID).update(options).then()
```

Because service.md says the signature of update is Service.update(opts, id)

**Comment by AgustinCB** [comment]
Yeah, you're right, the documentation is out of date. Good catch. 

Will fix that in the evening. Thanks for the heads up.

And yes, that should be the expected usage. I deprecated all the static functions that accept `id` as parameter to use instances created using the method `get` instead in this commit https://github.com/AgustinCB/docker-api/commit/865c8396b4a45a44eb8285027a9586a18deae390.

And evidently I forgot to update the docs.

**Comment by AgustinCB** [comment]
Same comment for remove and status.

**Comment by kanedauy** [comment]
For some reason when I do a get of a service (the service exists) I receive:
```
Service {
  data: {},
  modem:
   Modem {
     socketPath: '/var/run/docker.sock',
     host: undefined,
     port: undefined,
     version: undefined,
     key: undefined,
     cert: undefined,
     ca: undefined,
     timeout: undefined,
     checkServerIdentity: undefined,
     protocol: 'http' },
  id: 'j1j53b2map6o8w42dpavdga1k' }
```
And if I do an update the error is
```
err { Error: (HTTP code 400) unexpected - invalid service version '': strconv.ParseUint: parsing "": invalid syntax
```

The service I get is kind of... empty

**Comment by AgustinCB** [comment]
It should be empty. Note that it's only an instance with no information. If you want the actual content of the service you need to do:

```javascript
const service = await docker.service.get(SERVICE_ID).status()
console.log(service)
```

On the other hand, when you update a service you have to set a valid version to it. It can't be empty. See this line in the test: https://github.com/AgustinCB/docker-api/blob/master/test/swarm.js#L97

**Comment by AgustinCB** [comment]
However, I want to let you know that you don't usually need to get the status of an entity before updating. Services are kinda an special case because they need a valid version, usually dependant on the previous one. So you would have to get that, set the new one properly and then send the update.
