### ISSUE TITLE
partial file written to container

### ISSUE THREAD

**Issue by dcharbonnier** [AgustinCB/docker-api#20]
.then(() => container.fs.put(`${settings.TMP}/nginx.conf`, {path: settings.NGINX_CONF_PATH}))
the end of the file is truncated

Docker version 17.04.0-ce, build 4845c56

**Comment by dcharbonnier** [comment]
updated     "docker-modem": "^0.3.7", same problem

**Comment by AgustinCB** [comment]
DO you have the file you're trying to upload? Can you attach it, please? Thanks!

**Comment by dcharbonnier** [comment]
I can't give the original file, the full logic is :
```
return container.fs.get({path: `${settings.NGINX_CONF_PATH}/nginx.conf`})
    .then(promisifyStream)
    .then((conf) => {
      conf = conf.replace(settings.MATCH_UPSTREAM, upstreams)
      console.log(conf);
      return fs.writeFile(`${settings.TMP}/nginx.conf`, conf)
    })
    .then(() => container.fs.put(`${settings.TMP}/nginx.conf`, {path: settings.NGINX_CONF_PATH}))
    .then(promisifyStream)
    .then(() => container.kill({signal: settings.HUP}));
```
the console.log() show the full file, but if I cat the file in the container this file is truncated and this exact code was working with an other version of docker. (the regexp change something in the middle of the file, not at the end)

**Comment by dcharbonnier** [comment]
the fs.writeFile is coming from mz, it's a promise, the cat of the /tmp/nginx.conf is also ok

**Comment by AgustinCB** [comment]
Uhm, ok, I'll try to reproduce with the code tonight and let you know what I can find. Someone already reported some breaking changes in the new versions of docker, so it's more than probably that's the case again.

Thank you!

**Comment by dcharbonnier** [comment]
my file is 210 lines
-rw-rw-r-- 1 david david 10439 apr 11 19:33 n

I added blank lines to get to 1102 and the result is file of 1093 lines, 10 are missing but it's ok in my case...

**Comment by AgustinCB** [comment]
Ha! Smart workaround. I suspect it's a problem with the docker-modem dependency. I'll study a little bit that and see if I can fix it.

**Comment by dcharbonnier** [comment]
Yes I didn't saw anything that could be the root of the problem in this project, its probably docker-modem

**Comment by dcharbonnier** [comment]
put expect a tar stream not a file, using https://github.com/mafintosh/tar-stream works
