### ISSUE TITLE
Any way to get the Service Logs?

### ISSUE THREAD

**Issue by kanedauy** [AgustinCB/docker-api#21]
[https://docs.docker.com/engine/api/v1.26/#operation/ServiceLogs](https://docs.docker.com/engine/api/v1.26/#operation/ServiceLogs)

Any way to access this functionality?

**Comment by AgustinCB** [comment]
No right now. But will add. It's a good idea.

Thanks.

**Comment by AgustinCB** [comment]
This should be now in the new version. I'm not sure I was able to test it properly, so let me know if you find any error. Thank you man!

https://github.com/AgustinCB/docker-api/blob/master/test/swarm.js#L109

**Comment by kanedauy** [comment]
I'm trying this functionality and I'm having issues with the encoding.
To troubleshoot I set the locale in the docker image to en_US.UTF-8 (following http://www.roadsi.de/locales-on-ubuntu-in-docker.html)
Other thing I tried was to set 'content-type': 'text/plain; charset=utf-8', but I get some estrange chars, like ������
Any idea?

Thanks

**Comment by AgustinCB** [comment]
Arg, string encoding... Hate them. 

What service/container are you running?

**Comment by kanedauy** [comment]
FROM ubuntu:16.04

>docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

The locale setting had no effect at all.

**Comment by AgustinCB** [comment]
Just for the record, I don't think this is a problem with this package itself, but with either `docker-modem` or docker. But I need to confirm it. Let me run a couple experiments and come back to you with a better feedback or at least a work around. 

Thank you for the report!

**Comment by kanedauy** [comment]
If is of some use for you, with this you get to clean the log of not wanted chars

```JavaScript
const stripAnsi = require('strip-ansi')

// the first 8 chars of each line are garbage
logs = removeFirstChars(logs)
//remove ansi chars
let logs = JSON.stringify(stripAnsi(chunk))
//remove unicode chars
const reg = /\\u([0-9]|[a-fA-F])([0-9]|[a-fA-F])([0-9]|[a-fA-F])([0-9]|[a-fA-F])/g
logs = logs.replace(reg, '')
logs = JSON.parse(logs)

function removeFirstChars(str) {
  const reg = /^......../
  let res = ''
  const lines = str.split(/\n/)

  lines.forEach((line) => {
    line = line.replace(reg, '')
    res += line + '\n'
  })
  return res
}
```

**Comment by AgustinCB** [comment]
Thank y ou for your feedback and help. I'll see if I can spend some time on this tomorrow and try to handle this cases. Much appreciated!
