### ISSUE TITLE
Docker push to private registry getting failed.

### ISSUE THREAD

**Issue by Huma123** [AgustinCB/docker-api#24]
I created a docker image and tagged with myrepo.com/myapp:myapptag
But when i tried to push this, it always trying to push to https://registry-1.docker.io/v2/ not to my private registry

**Comment by AgustinCB** [comment]
Sounds like a legit bug. WIll take a look in the weekend (sorry, busy week). Do you a sample code to reproduce the issue? Thanks for the report!

**Comment by Huma123** [comment]
Hi,

     Thanks for responding.


     I might not be able to provide the full code but below is what I am
trying to do.

docker.image.get('myrepo.com/myapp:1.0.1')
.push(docker.auth({
    username: "my_username",
    password: "my_password"
}));

And error i am getting is
(node:3226) UnhandledPromiseRejectionWarning: Unhandled promise rejection
(rejection id: 1): Error: (HTTP code 401) unexpected - Get
https://registry-1.docker.io/v2/: unauthorized: incorrect username or
password


Thanks

**Comment by AgustinCB** [comment]
What works for me is:

```
docker.image.get('myrepo.com/myapp:1.0.1')
.push({
    username: "my_username",
    password: "my_password"
});
```

`docker.auth` is used to get test auth and get a token.

Can you check and let me know if it works?

**Comment by AgustinCB** [comment]
Following on https://github.com/AgustinCB/docker-api/issues/36
