### ISSUE TITLE
How to read stream of a command executed in Docker container?

### ISSUE THREAD

**Issue by DmitriyBerezin** [AgustinCB/docker-api#27]
How I can read an ouput stream of a command executed in Docker container? I try to use a code from example, but 'data' event is not fired at all. What I'm doing wrong? And is it possible to get a status code (success, fail...) of a command execution? Thank you.

Code examle:
```javascript
'use strict'

const Docker = require('node-docker-api').Docker

const _docker = new Docker()
let _container

const containerParams = {
	Image: 'docker-test-image',
	Tty: true
}
_docker.container.create(containerParams)
	.then((container) => container.start())
	.then((container) => {
		console.log('Container started')

		_container = container

		return _container.exec.create({
			Cmd: ['ls', '-ll']
		})
	})
	.then((exec) => {
		console.log('Exec created')

		return exec.start()
	})
	.then((stream) => {
		console.log('Container ID:', _container.id)
		console.log('Exec started')

		stream.on('readable', () => {
			console.log('onreadable')
		})
		stream.on('data', (data) => {
			console.log('Data from Docker has been obtained')
			console.log(data.toString())

			_container.kill()
		})
		stream.on('end', () => {
			console.log('onend')
		})
		stream.on('error', (err) => console.log(err))
	})
	.catch((err) =>  {
		console.log(err)
	})

```

**Comment by AgustinCB** [comment]
Hi! 

Yeah, the examples are out of date and with some errors. #28 should fix most of them. About the code, this should work: 

```javascript
'use strict'
const Docker = require('node-docker-api').Docker

const promisifyStream = (stream) => new Promise((resolve, reject) => {
  stream.on('data', (d) => console.log(d.toString()))
  stream.on('end', resolve)
  stream.on('error', reject)
})

let docker = new Docker({ socketPath: '/var/run/docker.sock' })
let _container

docker.container.create({
  Image: 'ubuntu',
  Cmd: [ '/bin/bash', '-c', 'tail -f /var/log/dmesg' ],
  name: 'test'
})
  .then((container) => container.start())
  .then((container) => {
    _container = container
    return container.exec.create({
      AttachStdout: true,
      AttachStderr: true,
      Cmd: [ 'echo', 'test' ]
    })
  })
  .then((exec) => {
    return exec.start({ Detach: false })
  })
  .then((stream) => promisifyStream(stream))
  .then(() => _container.kill())
  .catch((error) => console.log(error))
```

The most important changes is passing `AttachStdin` and `AttachStderr` when creating the exec and `Detach` set to false when we start the exec.

Basically we have to tell Docker that we want to listen to the standard in and standard error when executing the command.

Let me know if that works!

**Comment by DmitriyBerezin** [comment]
Yes, it works! Thank you!

**Comment by AgustinCB** [comment]
Thinking about this, it's a little unfortunate that you have to explicitly add `AttachStdout` when creating the exec. It isn't very intuitive and forces you to go to the docker API to understand what's going on.

What would you think about the `container.exec.create` setting that value to true by default? That would differ from the docker API, but make it easier for newcomers. 

Does it make sense?

**Comment by DmitriyBerezin** [comment]
Sorry for a delay. I think that a usage of docker API's defaults is more predictable for most developers. Since docker team declare exactly such defaults - there are some reasons I suppose.

As for me I am just in the beginning of a docker understanding and usage. What was strange for me for a first look - why when I create a new container with `AttachStdout  = true`, this ptoperty isn't inherited by exec properties.
