### ISSUE TITLE
Example is different than readme

### ISSUE THREAD

**Issue by OmgImAlexis** [AgustinCB/docker-api#30]
The example in https://github.com/AgustinCB/docker-api/blob/master/examples/list_containers.js wasn't updated to how the readme has it. 

```diff
-     stats.on('data', (stat) => console.log('Stats: ',stat))
+     stats.on('data', (stat) => console.log('Stats: ', stat.toString()))
```

https://github.com/AgustinCB/docker-api#list-inspect-and-stat-containers

**Comment by AgustinCB** [comment]
Good catch :)
