### ISSUE TITLE
Is there a way to add a volume when creating or starting a container?

### ISSUE THREAD

**Issue by OmgImAlexis** [AgustinCB/docker-api#33]
I'm trying to recreate this command using `docker-api` but I don't see anything at all about using volumes and the docs page isn't working.

```
docker run -d \
   -v $(pwd)/.caddy/php/Caddyfile:/etc/Caddyfile \
   -v $(pwd)/root/sites/user123/example.com/www:/srv \
   -v $(pwd)/root/sites/user123/example.com/logs:/logs \
   --name=example.com \
   abiosoft/caddy:php
```

**Comment by AgustinCB** [comment]
Well, the documentation of the project explains how to use the project. For detailed things like this, I'd refer to the docker api documentation. In this case:

https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate

You can add to the dictionary of option a key called Volumnes:

```
Volumes": {
"/volumes/data": { }
}
```

So you would so something like this: 

```
docker.container.create({
  Image: 'ubuntu',
  Cmd: [ '/bin/bash', '-c', 'tail -f /var/log/dmesg' ],
  Volumes": {
    "/volumes/data": { }
  },
  name: 'test'
})
```

**Comment by OmgImAlexis** [comment]
Oh okay I didn't realise it passed it through like that. Thanks.
