### ISSUE TITLE
`EISDIR: illegal operation on a directory` when the src includes subfolders

### ISSUE THREAD

**Issue by IniZio** [AgustinCB/docker-api#38]
I used `fs.readdirSync('somewhere')` as src in docker build image function, however it returns error if I have subfolders. Seems like the api readfilesync's all filenames, and thought the directory is a file too.

**Comment by AgustinCB** [comment]
Can you give me steps to reproduce, please? I'm not sure I fully understand how to arrive to the problem.

Thanks!

**Comment by IniZio** [comment]
Like if the directory structure of 'somewhere' is 
```
|somewhere
|--file1
|--folder2
|----file2.1
```
It returns error that folder2 is not a file

**Comment by IniZio** [comment]
𝖂𝖆𝖘𝖙𝖊𝖉
