### ISSUE TITLE
Error on pulling

### ISSUE THREAD

**Issue by jeroenpeeters** [AgustinCB/docker-api#4]
I tried the example for pulling images

     docker.image.create({ fromImage: 'ubuntu' })
        .then((stream) => promisifyStream(stream))
        .then(() => docker.image.status('ubuntu'))
        .then((image) => image.history())
        .then((events) => console.log(events))

However, I've seen that when you don't consume the stream, as is the case in your example, the end event is never fired.

When I log the data of the promisified stream, I get:

    {"status":"Downloading from http://"}
    {"errorDetail":{"message":"Get http://: http: no Host in request URL"},"error":"Get http://: http: no Host in   request URL"}

**Comment by AgustinCB** [comment]
Nice catch. Thank you, will take a look a fix it.

**Comment by jeroenpeeters** [comment]
What I actually wanted to say is is that even though I consume the stream, the image isn't being pulled. All I get are these error messages. Am I doing something wrong?

**Comment by AgustinCB** [comment]
Yeah, I know, it's an error in the README. I'm changing it right now. Meanwhile:

docker.image.create takes two arguments, the first one is the auth object for the registry. The second one are the parameters. In the demo, I wrote the parameters in the first one. So it should be:

`  docker.image.create({}, { fromImage: 'ubuntu' })`

Will commit a change once I check again all the examples. 

Thanks for the input

**Comment by AgustinCB** [comment]
By the way, better:

`docker.image.create({}, { fromImage: 'ubuntu' , tag: 'latest'})`

Otherwise it will download all the tags.

If you find any other mistake, please advice me!

**Comment by AgustinCB** [comment]
If fixed the examples and added more info to make them run. In this case, passing empty {} as a first argument is the solution. Closing this issue, but don't doubt in asking if it doesn't work.
