### ISSUE TITLE
yarn

### ISSUE THREAD

**Issue by dcharbonnier** [AgustinCB/docker-api#42]
Do you mind moving to yarn ? It's much faster

**Comment by AgustinCB** [comment]
Let me research exactly what that implies.

If I do it, I don't think I'll move to yarn, I'll probably maintain the two options.

**Comment by dcharbonnier** [comment]
the package-lock.json is already missing from the repository, yarn use a yarn.lock file, expect that it's pretty much the same, you can close it was just a way to get your attention on this topic
