### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by dcharbonnier** [AgustinCB/docker-api#9]
Would be super nice to have the typescript definition with the project

**Comment by AgustinCB** [comment]
It's actually not a bad idea. 

Will work on it. Thank you!

**Comment by shomodj** [comment]
If you need help/testing tsds let me know

**Comment by AgustinCB** [comment]
If you think you can handle the task, feel free to create a PR. I'm just learning the syntax and researching the proper way to do it.

**Comment by dcharbonnier** [comment]
WIP #13
